/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JFrame;
import java.util.Calendar;
import java.util.GregorianCalendar;

public class saleshome extends javax.swing.JFrame {
    int xMouse;
    int yMouse;
    int timerun = 0;

    
    public saleshome() {
        initComponents();
        new Thread(){
            public void run(){
                while (timerun==0) {
                    Calendar cal=new GregorianCalendar();
                    int hour=cal.get(Calendar.HOUR);
                    int min=cal.get(Calendar.MINUTE);
                    int sec=cal.get(Calendar.SECOND);
                    int AM_PM=cal.get(Calendar.AM_PM);
                    String d_n= "";
                    if (AM_PM==1) {
                        d_n="PM";
                    } else {
                        d_n="AM";
                    }
                    String time = hour + ":" + min + ":" + sec + d_n;
                    
                    timelabel.setText(time);
                    
                }
            }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logout = new javax.swing.JLabel();
        viewcurrentstock = new javax.swing.JLabel();
        searchproduct = new javax.swing.JLabel();
        newsale = new javax.swing.JLabel();
        productbooking = new javax.swing.JLabel();
        addcustomer = new javax.swing.JLabel();
        messageowner = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        timelabel = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                logoutMouseReleased(evt);
            }
        });
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 70, 60, 20));

        viewcurrentstock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewcurrentstock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                viewcurrentstockMouseReleased(evt);
            }
        });
        jPanel1.add(viewcurrentstock, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 160, 160));

        searchproduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchproduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                searchproductMouseReleased(evt);
            }
        });
        jPanel1.add(searchproduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, 160, 160));

        newsale.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newsale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                newsaleMouseReleased(evt);
            }
        });
        jPanel1.add(newsale, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 160, 160));

        productbooking.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        productbooking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                productbookingMouseReleased(evt);
            }
        });
        jPanel1.add(productbooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 160, 160));

        addcustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addcustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                addcustomerMouseReleased(evt);
            }
        });
        jPanel1.add(addcustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 160, 160));

        messageowner.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        messageowner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                messageownerMouseReleased(evt);
            }
        });
        jPanel1.add(messageowner, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, 160, 160));

        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                closeMouseReleased(evt);
            }
        });
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(768, 10, 25, 24));

        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                minimizeMouseReleased(evt);
            }
        });
        jPanel1.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 11, 24, 24));

        timelabel.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        timelabel.setForeground(new java.awt.Color(0, 51, 204));
        jPanel1.add(timelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 150, 20));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mobile/shop/management/sales_homepage.png"))); // NOI18N
        bg.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bgMouseDragged(evt);
            }
        });
        bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgMousePressed(evt);
            }
        });
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minimizeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseReleased
         this.setState(saleshome.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseReleased

    private void closeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseReleased
        dispose();
    }//GEN-LAST:event_closeMouseReleased

    private void bgMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_bgMouseDragged

    private void bgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMousePressed
        // TODxMouse = evt.getX();
    yMouse = evt.getY();
    xMouse = evt.getX();
    }//GEN-LAST:event_bgMousePressed

    private void logoutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseReleased
        dispose();
        loginpage lp=new loginpage();
        lp.setVisible(true);
        
    }//GEN-LAST:event_logoutMouseReleased

    private void viewcurrentstockMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewcurrentstockMouseReleased
        sales_viewstock vs = new sales_viewstock();
        vs.setVisible(true);dispose();
    }//GEN-LAST:event_viewcurrentstockMouseReleased

    private void newsaleMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newsaleMouseReleased
        sales_newsales ns = new sales_newsales();
        ns.setVisible(true);dispose();
    }//GEN-LAST:event_newsaleMouseReleased

    private void searchproductMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchproductMouseReleased
        sales_searchproduct sp = new sales_searchproduct();
        sp.setVisible(true);dispose();
    }//GEN-LAST:event_searchproductMouseReleased

    private void productbookingMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productbookingMouseReleased
        sales_bookproduct bp = new sales_bookproduct();
        bp.setVisible(true);dispose();
    }//GEN-LAST:event_productbookingMouseReleased

    private void addcustomerMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addcustomerMouseReleased
        sales_addcustomer ac = new sales_addcustomer();
        ac.setVisible(true);
    }//GEN-LAST:event_addcustomerMouseReleased

    private void messageownerMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_messageownerMouseReleased
        sales_messageowner mo = new sales_messageowner();
        mo.setVisible(true);dispose();
    }//GEN-LAST:event_messageownerMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(saleshome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(saleshome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(saleshome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(saleshome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new saleshome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addcustomer;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel close;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel messageowner;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel newsale;
    private javax.swing.JLabel productbooking;
    private javax.swing.JLabel searchproduct;
    private javax.swing.JLabel timelabel;
    private javax.swing.JLabel viewcurrentstock;
    // End of variables declaration//GEN-END:variables
}
