/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.sql.*;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import net.sf.jasperreports.*;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
/**
 *
 * @author Sreerag PR
 */
public class sales_newsales extends javax.swing.JFrame {

    /**
     * Creates new form newsales
     */String Date = "";
    public sales_newsales() {
        initComponents();
        int timerun=0;
        new Thread(){
            public void run(){
                while (timerun==0) {
                    Calendar cal=new GregorianCalendar();
                    int day=cal.get(Calendar.DATE);
                    int mon=cal.get(Calendar.MONTH)+1;
                    int year=cal.get(Calendar.YEAR);
                    Date = day + "-" + mon + "-" + year ;
                    String time = "Date : " + Date;
                    date.setText(time);
                    
                }
            }
        }.start();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","");
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from customer");
            while (rs.next()) {                
                customer.addItem(rs.getString("name"));
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tot = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        costomer = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        customer = new javax.swing.JComboBox<>();
        product = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        brand = new javax.swing.JComboBox<>();
        Model = new javax.swing.JComboBox<>();
        quantity = new javax.swing.JSpinner();
        date = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tot1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        tot2 = new javax.swing.JLabel();

        tot.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tot.setText("0");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("NEW SALE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 11, -1, 39));

        costomer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        costomer.setText("Customer");
        jPanel1.add(costomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Product");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Quantity");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        customer.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                customerItemStateChanged(evt);
            }
        });
        customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerActionPerformed(evt);
            }
        });
        jPanel1.add(customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 172, -1));

        product.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                productItemStateChanged(evt);
            }
        });
        product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productActionPerformed(evt);
            }
        });
        jPanel1.add(product, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 172, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Brand");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Model");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        brand.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                brandItemStateChanged(evt);
            }
        });
        jPanel1.add(brand, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 172, -1));

        Model.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ModelItemStateChanged(evt);
            }
        });
        Model.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModelActionPerformed(evt);
            }
        });
        jPanel1.add(Model, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 170, -1));

        quantity.setModel(new javax.swing.SpinnerNumberModel(0, 0, 30, 1));
        quantity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                quantityStateChanged(evt);
            }
        });
        jPanel1.add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 222, 70, -1));

        date.setFont(new java.awt.Font("DS-Digital", 0, 18)); // NOI18N
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 150, 20));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Sale");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer", "Product", "Brand", "Model", "Quantity", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTable1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Net Amount");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Total Amount");

        tot1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tot1.setText("0");

        jButton3.setText("Remove Item");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel8.setText("Add");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel8MouseReleased(evt);
            }
        });

        tot2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tot2.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tot2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tot1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addGap(350, 350, 350)
                            .addComponent(jButton2))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tot2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tot1)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        saleshome sh = new saleshome();
        sh.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModelActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       try{
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","");
             int d = JOptionPane.YES_NO_OPTION;
            int ds = JOptionPane.showConfirmDialog(null,"Are You Sure Want To Sell The Item?","Warning",d);
            if (ds==0) {
            for (int i = 0; i < model.getRowCount(); i++) {
                String q;
                String a;
                String Customer =(String) model.getValueAt(i, 0);
                System.out.println("e1");
                String Brand = (String) model.getValueAt(i, 1);
                System.out.println("e2");
                String Model = (String) model.getValueAt(i, 2);
                System.out.println("e3");
                String Product = (String) model.getValueAt(i, 3);
                System.out.println("e4");
                q =  (String) model.getValueAt(i, 4);
                System.out.println("e5");
                a = (String) model.getValueAt(i, 5);
                System.out.println("e6");
            PreparedStatement pt = con.prepareStatement("insert into sales (customer,brand,model,product,quantity,amount,date) values (?,?,?,?,?,?,?)");
                System.out.println("pp0");
            pt.setString(1, Customer);
            pt.setString(2, Brand);
            pt.setString(3,Model);
            pt.setString(4,Product);
            pt.setString(5,q);
            pt.setString(6,a);
            pt.setString(7,Date);
            pt.executeUpdate();
            String quant = Integer.toString((int) quantity.getValue());
            /*Map<String,Object> params = new HashMap<>();
            params.put("name",customer.getSelectedItem());
            params.put("product",product.getSelectedItem());
            params.put("brand",brand.getSelectedItem());
            params.put("model",this.Model.getSelectedItem());
            params.put("name",customer.getSelectedItem());
            params.put("quantity",quant);
            params.put("tot",tot1.getText());
            params.put("date", date.getText());
            JasperDesign jd = JRXmlLoader.load("report/salesbill.jrxml");
            JasperReport jp = JasperCompileManager.compileReport(jd);
          //JRDataSource datasource = new JRTableModelDataSource(jTable1.getModel());
            JasperPrint print = JasperFillManager.fillReport(jp,params,new JREmptyDataSource());
            JasperViewer.viewReport(print,true);*/
            
            }
            JOptionPane.showMessageDialog(null,"Sale Has Been Registedred");
            Map<String,Object> params = new HashMap<>();
            params.put("total",tot1.getText());
            DefaultTableModel de = (DefaultTableModel) jTable1.getModel();
            JRTableModelDataSource datasource = new JRTableModelDataSource(de);
            String reportname = "report/salebill.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(reportname);
            JasperPrint jp = JasperFillManager.fillReport(jr,params,datasource);
            JasperViewer.viewReport(jp);
            }
            else{
                JOptionPane.showMessageDialog(null,"Cancelled");
            }
            
           /*DefaultTableModel df = (DefaultTableModel) jTable1.getModel();
            JRTableModelDataSource dataSource = new JRTableModelDataSource(df);
            String rs = "src/ui/salesbill.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(rs);
            Map<String,Object> params = new HashMap<String,Object>();
            params.put("title1","title1");
            JasperPrint jp = JasperFillManager.fillReport(jr, params,dataSource);
            */
            
            
       }
       catch(Exception e){
           //JOptionPane.showMessageDialog(null, "Error Please Check The Data You Have Entered");
           System.out.println(e);
           
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void quantityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_quantityStateChanged
        tot.setText("0");
        Integer p,q,r = 0;
        String b = (String) brand.getSelectedItem();
        String m = (String) Model.getSelectedItem();
        String pn = (String) product.getSelectedItem();         
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","");
            PreparedStatement stmt = con.prepareStatement("select price from salesstock where brand = ? and model = ? and productname = ? ");
            stmt.setString(1, b);
            stmt.setString(2, m);
            stmt.setString(3, pn);
            ResultSet rs = stmt.executeQuery();
            while (rs.next()) {
                p = rs.getInt("price");
                q = (Integer) quantity.getValue();
                r=p*q;
                tot2.setText(Integer.toString(r));
            }
        } catch (Exception e) {
            System.out.println("vc");
            System.out.println(e);
        }
       
    }//GEN-LAST:event_quantityStateChanged

    private void productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productActionPerformed

    private void productItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_productItemStateChanged
        try {
            tot.setText("0");
            String p = (String) product.getSelectedItem();
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","");
            PreparedStatement stmt;
            stmt = con.prepareStatement("select * from salesstock where productname = ? ");
            stmt.setString(1, (String) product.getSelectedItem());
            ResultSet rs = stmt.executeQuery();
            while (rs.next()) {   
                brand.removeAllItems();
                brand.addItem(rs.getString("brand"));
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_productItemStateChanged

    private void customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerActionPerformed

    private void customerItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_customerItemStateChanged
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","");
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from salesstock");
            while (rs.next()) {                
                product.addItem(rs.getString("productname"));
            }
        } catch (Exception e) {
            System.out.println(e);                   
        }
    }//GEN-LAST:event_customerItemStateChanged

    private void brandItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_brandItemStateChanged
         try {
             tot.setText("0");
            String p = (String) product.getSelectedItem();
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","");
            PreparedStatement stmt;
            stmt = con.prepareStatement("select * from salesstock where brand = ? ");
            stmt.setString(1, (String) brand.getSelectedItem());
            ResultSet rs = stmt.executeQuery();
            while (rs.next()) {   
                Model.removeAllItems();
                Model.addItem(rs.getString("model"));
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_brandItemStateChanged

    private void jLabel8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseReleased
        int abc = 0;
        try {
            String q = Integer.toString((int) quantity.getValue());
            String am = (String) tot2.getText();
            Object[] row = new Object[]{customer.getSelectedItem(),product.getSelectedItem(),brand.getSelectedItem(),Model.getSelectedItem(),q,am};
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.addRow(row);
            for (int i = 0; i < model.getRowCount(); i++) {
                int total = 0;
                String a = (String) model.getValueAt(i, 5);
                Integer b = Integer.parseInt(a);
                abc=abc+b;
                System.out.println(abc);
                tot1.setText(Integer.toString(abc));
                        }
            
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jLabel8MouseReleased

    private void ModelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ModelItemStateChanged
        tot.setText("0");
        quantity.setValue(0);
    }//GEN-LAST:event_ModelItemStateChanged

    private void jTable1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTable1AncestorAdded
       // while (jTable1.getColumnName(5)) {            
            
       // }
    }//GEN-LAST:event_jTable1AncestorAdded

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            int abc = 0;
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            if (model.getRowCount()==0){
                tot1.setText("0");
                JOptionPane.showMessageDialog(null,"No Item Is Selected");
            }
            else {
            model.removeRow(jTable1.getSelectedRow());
            for (int i = 0; i < model.getRowCount(); i++) {
                int total = 0;
                String a = (String) model.getValueAt(i, 5);
                Integer b = Integer.parseInt(a);
                abc=abc+b;
                System.out.println(abc);
                tot1.setText(Integer.toString(abc));
                }
            }
        } catch (Exception e) {
            
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sales_newsales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sales_newsales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sales_newsales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sales_newsales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sales_newsales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Model;
    private javax.swing.JComboBox<String> brand;
    private javax.swing.JLabel costomer;
    private javax.swing.JComboBox<String> customer;
    private javax.swing.JLabel date;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> product;
    private javax.swing.JSpinner quantity;
    private javax.swing.JLabel tot;
    private javax.swing.JLabel tot1;
    private javax.swing.JLabel tot2;
    // End of variables declaration//GEN-END:variables
}
